name: A New Career in a New Town
favicon: null
layout_spectrum: 0.00098
typography_spectrum: 0.04785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1b1b1b'
    - '#373737'
    - '#b1b1b1'
    - '#777777'
  brandStrength: 0.3014949450735003
  lightness: 0.17547368654049933
  saturation: 0.2795496841426939
  rhythmicContrast: 0.10190679668448865
purpose: []
